#ifndef SUISHO_CORE_INTERNAL_FOREACH_MACRO_H_
#define SUISHO_CORE_INTERNAL_FOREACH_MACRO_H_

#define SUISHO_EXPAND(x) x

#define SUISHO_FOREACH_VA_ARGS_IMPL_1(f, arg) \
    f(arg)

#define SUISHO_FOREACH_VA_ARGS_IMPL_2(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_1(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_3(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_2(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_4(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_3(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_5(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_4(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_6(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_5(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_7(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_6(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_8(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_7(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_9(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_8(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_10(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_9(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_11(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_10(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_12(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_11(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_13(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_12(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_14(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_13(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_15(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_14(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_16(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_15(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_17(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_16(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_18(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_17(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_19(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_18(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_20(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_19(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_21(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_20(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_22(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_21(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_23(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_22(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_24(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_23(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_25(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_24(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_26(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_25(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_27(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_26(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_28(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_27(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_29(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_28(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_30(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_29(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_31(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_30(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_32(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_31(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_33(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_32(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_34(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_33(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_35(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_34(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_36(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_35(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_37(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_36(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_38(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_37(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_39(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_38(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_40(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_39(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_41(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_40(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_42(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_41(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_43(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_42(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_44(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_43(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_45(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_44(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_46(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_45(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_47(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_46(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_48(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_47(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_49(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_48(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_50(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_49(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_51(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_50(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_52(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_51(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_53(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_52(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_54(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_53(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_55(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_54(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_56(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_55(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_57(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_56(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_58(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_57(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_59(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_58(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_60(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_59(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_61(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_60(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_62(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_61(f, __VA_ARGS__))

#define SUISHO_FOREACH_VA_ARGS_IMPL_63(f, arg, ...) \
    f(arg) SUISHO_EXPAND(SUISHO_FOREACH_VA_ARGS_IMPL_62(f, __VA_ARGS__))

#define SUISHO_VA_ARGS_SIZE_IMPL2(\
    arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, \
    arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, \
    arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, \
    arg30, arg31, arg32, arg33, arg34, arg35, arg36, arg37, arg38, arg39, \
    arg40, arg41, arg42, arg43, arg44, arg45, arg46, arg47, arg48, arg49, \
    arg50, arg51, arg52, arg53, arg54, arg55, arg56, arg57, arg58, arg59, \
    arg60, arg61, arg62, arg63, N, ... \
)   N
#define SUISHO_VA_ARGS_SIZE_IMPL(...) SUISHO_EXPAND(SUISHO_VA_ARGS_SIZE_IMPL2(__VA_ARGS__))

#define SUISHO_FOREACH_INDICES() \
    64, 63, 62, 61, 60, 59, 58, 57, 56, 55, \
    54, 53, 52, 51, 50, 49, 48, 47, 46, 45, \
    44, 43, 42, 41, 40, 39, 38, 37, 36, 35, \
    34, 33, 32, 31, 30, 29, 28, 27, 26, 25, \
    24, 23, 22, 21, 20, 19, 18, 17, 16, 15, \
    14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0
#define SUISHO_VA_ARGS_SIZE(...) SUISHO_VA_ARGS_SIZE_IMPL(__VA_ARGS__, SUISHO_FOREACH_INDICES())

#define SUISHO_CAT_MACRO_IMPL(a, b) a ## b
#define SUISHO_CAT_MACRO(a, b) SUISHO_CAT_MACRO_IMPL(a, b)
#define SUISHO_FOREACH_VA_ARGS(f, ...) \
    SUISHO_EXPAND(SUISHO_CAT_MACRO(SUISHO_FOREACH_VA_ARGS_IMPL_, SUISHO_VA_ARGS_SIZE(__VA_ARGS__))(f, __VA_ARGS__))

#endif
